#[derive(Debug, Clone, PartialOrd, PartialEq)]
pub struct DIVE {
    pub bacdive_id: String,
    pub ncbi_tax_id: String,
    pub ncbi_associated_level: String,
    pub rrdna16s_accession: String,
    pub taxonomy_upd_method: String,
    pub phylum: String,
    pub class: String,
    pub order: String,
    pub family: String,
    pub genus: String,
    pub species: String,
    pub rest: String,
}

#[derive(Debug, Clone, PartialOrd, PartialEq)]
pub struct DIVEOUT {
    pub bacdivename: String,
    pub ncbi_tax_id_name: String,
    pub ncbi_associated_level_name: String,
    pub rrdna16s_accession_name: String,
    pub taxonomy_upd_method_name: String,
    pub phylum_name: String,
    pub class_name: String,
    pub order_name: String,
    pub family_name: String,
    pub genus_name: String,
    pub species_name: String,
    pub rest_name: String,
    pub bacdive_id: String,
    pub ncbi_tax_id: String,
    pub ncbi_associated_level: String,
    pub rrdna16s_accession: String,
    pub taxonomy_upd_method: String,
    pub phylum: String,
    pub class: String,
    pub order: String,
    pub family: String,
    pub genus: String,
    pub species: String,
    pub rest: String,
    pub bacdive_id_genus: String,
    pub ncbi_tax_id_genus: String,
    pub ncbi_associated_level_genus: String,
    pub rrdna16s_accession_genus: String,
    pub taxonomy_upd_method_genus: String,
    pub phylum_genus: String,
    pub class_genus: String,
    pub order_genus: String,
    pub family_genus: String,
    pub genus_genus: String,
    pub species_genus: String,
    pub rest_genus: String,
    pub bacdive_id_species: String,
    pub ncbi_tax_id_species: String,
    pub ncbi_associated_level_species: String,
    pub rrdna16s_accession_species: String,
    pub taxonomy_upd_method_species: String,
    pub phylum_species: String,
    pub class_species: String,
    pub order_species: String,
    pub family_species: String,
    pub genus_species: String,
    pub species_species: String,
    pub rest_species: String,
}
